domain_path: D:\vitis\us+\thesis_v3_500mhz_pf\export\thesis_v3_500mhz_pf\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
