domain_path: D:\vitis\ethnet_iwip_ps\export\ethnet_iwip_ps\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
